# Generated by Django 5.2 on 2025-04-17 17:12

from django.db import migrations


def add_initial_users(apps, schema_editor):
    User = apps.get_model("app", "User")
    User.objects.create(
        name="Alice", email="alice@email.com", age=25, ssn="123-45-6789"
    )
    User.objects.create(name="Bob", email="bob@email.com", age=25, ssn="223-45-6789")
    User.objects.create(
        name="Carmen", email="carmen@email.com", age=25, ssn="323-45-6789"
    )
    User.objects.create(
        name="David", email="david@email.com", age=25, ssn="423-45-6789"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_age"),
    ]

    operations = [
        migrations.RunPython(add_initial_users),
    ]
